* TI84 Plus Basic programs
TODO: any info on building + running?


[[https://github.com/miselin/tibasic][TIBasic]] is used for building to a format the calculator understands. After building, the =.8xp= files can be transferred to the calculator directly. I just use the file names (without the extension) as the program names.


** Program info
Here I try to mention any relevant information on the programs.

*** x2solve
Quadratic equation solver. =AX^2 + BX + C = 0= Handles linear equations as well with =A=0=.

*** dot
Warning: Uses A and B matrix slots, and therefore overrides them even if they are currently in use.

*** getcol
Get a column C from a matrix. Fill in expected column in Ans, and matrix in matrix slot A. Uses matrix slot I for storage.


Result is found in Ans.

*** QRDecomp
QR factorization/decomposition using Gram Schmidt process. Uses way too many matrix slots as working variables while calculating the Gram Schmidt process. Can probably be optimized. TI Basic gets hard to read once programs get big... Calculates result in matrix slot B and C.
